;; *************************************
;; Base de Conocimiento
;; *************************************
;;==== Número de tuplas de conocimiento===
113
;;========== Conocimiento  ================
((id . 0)  (Clase . Persona) (Nombre . Francis-Ford-Coppola) (Nacionalidad . Estadounidense) (Año-Nacimiento . 1939))
((id . 1)  (Clase . Persona) (Nombre . Victor-Fleming)       (Nacionalidad . Estadounidense) (Año-Nacimiento . 1889))
((id . 2)  (Clase . Persona) (Nombre . Quentin-Tarantino)    (Nacionalidad . Estadounidense) (Año-Nacimiento . 1963))
((id . 3)  (Clase . Persona) (Nombre . Robert-Zemeckis)      (Nacionalidad . Estadounidense) (Año-Nacimiento . 1952))
((id . 4)  (Clase . Persona) (Nombre . Stanley-Kubrick)      (Nacionalidad . Estadounidense) (Año-Nacimiento . 1928))
((id . 5)  (Clase . Persona) (Nombre . John-Lasseter)        (Nacionalidad . Estadounidense) (Año-Nacimiento . 1957))
((id . 6)  (Clase . Persona) (Nombre . Andy-Wachowski)       (Nacionalidad . Estadounidense) (Año-Nacimiento . 1967))
((id . 7)  (Clase . Persona) (Nombre . James-Cameron)        (Nacionalidad . Canadiense)     (Año-Nacimiento . 1954))
((id . 8)  (Clase . Persona) (Nombre . Steven-Spielberg)     (Nacionalidad . Estadounidense) (Año-Nacimiento . 1946))
((id . 9)  (Clase . Persona) (Nombre . Martin-Scorsese)      (Nacionalidad . Estadounidense) (Año-Nacimiento . 1942))
((id . 10) (Clase . Persona) (Nombre . Rob-Minkoff)          (Nacionalidad . Estadounidense) (Año-Nacimiento . 1962))
((id . 11) (Clase . Persona) (Nombre . Ridley-Scott)         (Nacionalidad . Británico)      (Año-Nacimiento . 1937))
((id . 12) (Clase . Persona) (Nombre . Ivan-Reitman)         (Nacionalidad . Canadiense)     (Año-Nacimiento . 1946))
((id . 13) (Clase . Persona) (Nombre . Andrew-Stanton)       (Nacionalidad . Estadounidense) (Año-Nacimiento . 1965))
((id . 14) (Clase . Persona) (Nombre . Peter-Jackson)        (Nacionalidad . Neozelandés)    (Año-Nacimiento . 1961))
((id . 15) (Clase . Persona) (Nombre . Christopher-Nolan)    (Nacionalidad . Estadounidense) (Año-Nacimiento . 1970))
((id . 16) (Clase . Persona) (Nombre . John-G-Avildsen)      (Nacionalidad . Estadounidense) (Año-Nacimiento . 1935))
((id . 17) (Clase . Persona) (Nombre . Gullermo-del-Toro)    (Nacionalidad . Mexicano)       (Año-Nacimiento . 1964))
((id . 18) (Clase . Película) (Nombre . The-Godfather)         (Estreno . 1972))
((id . 19) (Clase . Película) (Nombre . Wizard-of-Oz)          (Estreno . 1939))
((id . 20) (Clase . Película) (Nombre . Pulp-Fiction)          (Estreno . 1994))
((id . 21) (Clase . Película) (Nombre . Back-to-the-future)    (Estreno . 1985))
((id . 22) (Clase . Película) (Nombre . Forrest-Gump)          (Estreno . 1994))
((id . 23) (Clase . Película) (Nombre . A-Clockwork-Orange)    (Estreno . 1971))
((id . 24) (Clase . Película) (Nombre . The-Shining)           (Estreno . 1980))
((id . 25) (Clase . Película) (Nombre . Toy-Story)             (Estreno . 1995))
((id . 26) (Clase . Película) (Nombre . The-Matrix)            (Estreno . 1999))
((id . 27) (Clase . Película) (Nombre . Titanic)               (Estreno . 1997))
((id . 28) (Clase . Película) (Nombre . Avatar)                (Estreno . 2009))
((id . 29) (Clase . Película) (Nombre . Jurassic-Park)         (Estreno . 1993))
((id . 30) (Clase . Película) (Nombre . Taxi-Driver)           (Estreno . 1976))
((id . 31) (Clase . Película) (Nombre . The-lion-king)         (Estreno . 1994))
((id . 32) (Clase . Película) (Nombre . Gladiator)             (Estreno . 2000))
((id . 33) (Clase . Película) (Nombre . Ghostbusters)          (Estreno . 1984))
((id . 34) (Clase . Película) (Nombre . Wall-E)                (Estreno . 2008))
((id . 35) (Clase . Película) (Nombre . The-Lord-of-the-Rings) (Estreno . 2001))
((id . 36) (Clase . Película) (Nombre . Inception)             (Estreno . 2010))
((id . 37) (Clase . Película) (Nombre . Rocky)                 (Estreno . 1976))
((id . 38) (Clase . Película) (Nombre . Pan’s-Labyrinth)       (Estreno . 2006))
((id . 39) (Clase . Relación) (etiq . Dirigió) (Nombre . Francis-Ford-Coppola) (Nombre . The-Godfather))
((id . 40) (Clase . Relación) (etiq . Dirigió) (Nombre . Victor-Fleming)       (Nombre . Wizard-of-Oz))
((id . 41) (Clase . Relación) (etiq . Dirigió) (Nombre . Quentin-Tarantino)    (Nombre . Pulp-Fiction))
((id . 42) (Clase . Relación) (etiq . Dirigió) (Nombre . Robert-Zemeckis)      (Nombre . Back-to-the-future))
((id . 43) (Clase . Relación) (etiq . Dirigió) (Nombre . Robert-Zemeckis)      (Nombre . Forrest-Gump))
((id . 44) (Clase . Relación) (etiq . Dirigió) (Nombre . Stanley-Kubrick)      (Nombre . A-Clockwork-Orange))
((id . 45) (Clase . Relación) (etiq . Dirigió) (Nombre . Stanley-Kubrick)      (Nombre . The-Shining))
((id . 46) (Clase . Relación) (etiq . Dirigió) (Nombre . John-Lasseter)        (Nombre . Toy-Story))
((id . 47) (Clase . Relación) (etiq . Dirigió) (Nombre . Andy-Wachowski)       (Nombre . The-Matrix))
((id . 48) (Clase . Relación) (etiq . Dirigió) (Nombre . James-Cameron)        (Nombre . Titanic))
((id . 49) (Clase . Relación) (etiq . Dirigió) (Nombre . James-Cameron)        (Nombre . Avatar))
((id . 50) (Clase . Relación) (etiq . Dirigió) (Nombre . Steven-Spielberg)     (Nombre . Jurassic-Park))
((id . 51) (Clase . Relación) (etiq . Dirigió) (Nombre . Martin-Scorsese)      (Nombre . Taxi-Driver))
((id . 52) (Clase . Relación) (etiq . Dirigió) (Nombre . Rob-Minkoff)          (Nombre . The-lion-king))
((id . 53) (Clase . Relación) (etiq . Dirigió) (Nombre . Ridley-Scott)         (Nombre . Gladiator))
((id . 54) (Clase . Relación) (etiq . Dirigió) (Nombre . Ivan-Reitman)         (Nombre . Ghostbusters))
((id . 55) (Clase . Relación) (etiq . Dirigió) (Nombre . Andrew-Stanton)       (Nombre . Wall-E))
((id . 56) (Clase . Relación) (etiq . Dirigió) (Nombre . Peter-Jackson)        (Nombre . The-Lord-of-the-Rings))
((id . 57) (Clase . Relación) (etiq . Dirigió) (Nombre . Christopher-Nolan)    (Nombre . Inception))
((id . 58) (Clase . Relación) (etiq . Dirigió) (Nombre . John-G-Avildsen)      (Nombre . Rocky))
((id . 59) (Clase . Relación) (etiq . Dirigió) (Nombre . Gullermo-del-Toro)    (Nombre . Pan’s-Labyrinth))
((id . 60) (Clase . Persona) (Nombre . Dante-Alighieri)    (Nacionalidad . Italiano)       (Año-Nacimiento . 1265))
((id . 61) (Clase . Persona) (Nombre . Cervantes-Saavedra) (Nacionalidad . Española)       (Año-Nacimiento . 1547))
((id . 62) (Clase . Persona) (Nombre . Charles-Dickens)    (Nacionalidad . Británico)      (Año-Nacimiento . 1812))
((id . 63) (Clase . Persona) (Nombre . Homero)             (Nacionalidad . Griego)         (Año-Nacimiento . 0000))
((id . 64) (Clase . Persona) (Nombre . Franz-Kafka)        (Nacionalidad . Checoslovaquia) (Año-Nacimiento . 1924))
((id . 65) (Clase . Persona) (Nombre . Edgar-Allan-Poe)    (Nacionalidad . Estadounidense) (Año-Nacimiento . 1809))
((id . 66) (Clase . Persona) (Nombre . Jaime-Sabines)      (Nacionalidad . Mexicano)       (Año-Nacimiento . 1926))
((id . 67) (Clase . Persona) (Nombre . Stephen-King)       (Nacionalidad . Estadounidense) (Año-Nacimiento . 1947))
((id . 68) (Clase . Libro) (Título . Divina-Comedia))
((id . 69) (Clase . Libro) (Título . Don-Quijote-de-la-Mancha))
((id . 70) (Clase . Libro) (Título . Grandes-Esperanzas))
((id . 71) (Clase . Libro) (Título . Ilíada))
((id . 72) (Clase . Libro) (Título . Odisea))
((id . 73) (Clase . Libro) (Título . Relatos-cortos))
((id . 74) (Clase . Libro) (Título . El-proceso))
((id . 75) (Clase . Libro) (Título . El-castillo))
((id . 76) (Clase . Libro) (Título . La-metamorfosis))
((id . 77) (Clase . Libro) (Título . El-cuervo))
((id . 78) (Clase . Libro) (Título . El-corazón-delator))
((id . 79) (Clase . Libro) (Título . Ligeia))
((id . 80) (Clase . Libro) (Título . La-caja-oblonga))
((id . 81) (Clase . Libro) (Título . El-gato-negro))
((id . 82) (Clase . Libro) (Título .  Los-amorosos))
((id . 83) (Clase . Libro) (Título .  La-señal))
((id . 84) (Clase . Libro) (Título .  Uno-es-poeta))
((id . 85) (Clase . Libro) (Título .  El-resplandor))
((id . 86) (Clase . Libro) (Título .  Carrie))
((id . 87) (Clase . Libro) (Título .  Dr-sueño))
((id . 88) (Clase . Libro) (Título .  Misery))
((id . 89) (Clase . Libro) (Título .  It))
((id . 90)(Clase . Relación)(etiq . Escribió)(Nombre . Dante-Alighieri)     (Título . Divina-Comedia))
((id . 91)(Clase . Relación)(etiq . Escribió)(Nombre . Cervantes-Saavedra)  (Título . Don-Quijote-de-la-Mancha))
((id . 92)(Clase . Relación)(etiq . Escribió)(Nombre . Charles-Dickens)     (Título . Grandes-Esperanzas))
((id . 93)(Clase . Relación)(etiq . Escribió)(Nombre . Homero)              (Título . Ilíada))
((id . 94)(Clase . Relación)(etiq . Escribió)(Nombre . Homero)              (Título . Odisea))
((id . 95)(Clase . Relación)(etiq . Escribió)(Nombre . Franz-Kafka)         (Título . Relatos-cortos))
((id . 96)(Clase . Relación)(etiq . Escribió)(Nombre . Franz-Kafka)         (Título . El-proceso))
((id . 97)(Clase . Relación)(etiq . Escribió)(Nombre . Franz-Kafka)         (Título . El-castillo))
((id . 98)(Clase . Relación)(etiq . Escribió)(Nombre . Franz-Kafka)         (Título . La-metamorfosis))
((id . 99)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . El-cuervo))
((id . 100)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . El-corazón-delator))
((id . 101)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . Ligeia))
((id . 102)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . La-caja-oblonga))
((id . 103)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . La-caída-de-la-Casa-Usher))
((id . 104)(Clase . Relación)(etiq . Escribió)(Nombre . Edgar-Allan-Poe)     (Título . El-gato-negro))
((id . 105)(Clase . Relación)(etiq . Escribió)(Nombre . Jaime-Sabines)       (Título .  Los-amorosos))
((id . 106)(Clase . Relación)(etiq . Escribió)(Nombre . Jaime-Sabines)       (Título .  La-señal))
((id . 107)(Clase . Relación)(etiq . Escribió)(Nombre . Jaime-Sabines)       (Título .  Uno-es-poeta))
((id . 108)(Clase . Relación)(etiq . Escribió)(Nombre . Stephen-King)        (Título .  El-resplandor))
((id . 109)(Clase . Relación)(etiq . Escribió)(Nombre . Stephen-King)        (Título .  Carrie))
((id . 110)(Clase . Relación)(etiq . Escribió)(Nombre . Stephen-King)        (Título .  Dr-sueño))
((id . 111)(Clase . Relación)(etiq . Escribió)(Nombre . Stephen-King)        (Título .  Misery))
((id . 112)(Clase . Relación)(etiq . Escribió)(Nombre . Stephen-King)       (Título .  It))